// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plophztpccrdahcbddex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsb3BoenRwY2NyZGFoY2JkZGV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNDAwNTYsImV4cCI6MjA2MTgxNjA1Nn0.v3q1-bHPTx1ZtyoPmEsVBbhcTM6XViVMcmVBAMYSALs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);